(in-package :user)
(defun load-project ()
  (load "./Endereco.lsp")
  (load "./Pessoa.lsp")
  (load "./Solicitante.lsp")
  (load "./Executante.lsp")
  (load "./OrdemServico.lsp")
  (load "./TelaInicial.lsp")
)
(load-project)

